### ISSUE TITLE
(win7) Linking ws2_32

### ISSUE THREAD

**Issue by Kermer** [jrimclean/gdnet#1]
Using MinGW it works fine.
Using VisualStudio it can't find it.

In enet\SCSub
MinGW requires `env.Append(LIBS=['ws2_32'])`
VisualStudio requires `env.Append(LINKFLAGS=["ws2_32.lib"])` instead of it

**Comment by empyreanx** [comment]
Does it still work with MinGW after the change? I don't have time to do a lot of testing these days.

**Comment by rdcklinux** [comment]
If LINKFLAGS is a list add both. is posible?

**Comment by Kermer** [comment]
@jrimclean No, it doesn't. I think the best way would be to check which one is used to compile and then use the correct line, but I don't know how to check this.

**Comment by empyreanx** [comment]
@Kermer Godot's build system is rather murky and I'm not an expert with SCons, but I'll see if there's a variable that reveals which compiler is being used. I should be able to do some work this weekend. I hope this isn't urgent?

@rdcklinux It might be possible to add one library to LIBS and one to LINKFLAGS, but the linker will probably complain that it can't find the file.

**Comment by empyreanx** [comment]
@Kermer It would help if you could give me a brief description of how you setup your project in VS and which version you're using.

**Comment by empyreanx** [comment]
@Kermer I found something that might be useful: http://stackoverflow.com/questions/1961164/how-can-i-set-options-in-sconstruct-for-c-compiler-depending-on-compiler-type

**Comment by Kermer** [comment]
```
if (env['platform'] == 'windows'):
    if (env['CC'] == 'cl'):
        env.Append(LINKFLAGS=["ws2_32.lib"])
    else: # gcc mostly
        env.Append(LIBS=['ws2_32'])
```

This should fix it
